spring:
  application:
    name: rms
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_hibernate_db
    username: root
    password: 1234
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.hbm2ddl.import_files: sample_data.sql